// packages/ripple-ui-react/src/components/content/RplContent.tsx
import { type PropsWithChildren, type ReactNode } from 'react'

type Props = {
  html?: string
  children?: ReactNode
}

export function RplContent(props: PropsWithChildren<Props>) {
  const { html, children } = props
  if (html) {
    return (
      <div
        className='rpl-content'
        dangerouslySetInnerHTML={{ __html: html ?? '' }}
      />
    )
  } else {
    return <div className='rpl-content'>{children}</div>
  }
}

export default RplContent

// packages/ripple-ui-core/src/components/content/RplContent.vue
<script setup lang="ts">
type RplContentProps = {
  html?: string
  pageBackground?: string
}

defineProps<RplContentProps>()
</script>

<template>
  <div v-if="html" class="rpl-content" v-html="html"></div>
  <div v-else class="rpl-content">
    <slot></slot>
  </div>
</template>

<style src="./RplContent.css" />
