// packages/ripple-ui-react/src/components/button/RplButton.tsx
import type { ElementType, PropsWithChildren } from 'react'
import {
  rplButtonDefaults,
  type RplButtonProps
} from '@dpc-sdp/ripple-ui-shared/contracts'
import '@dpc-sdp/ripple-ui-styles/components/button/RplButton.css'

type RplButtonComponentProps = PropsWithChildren<RplButtonProps>

export const RplButton = (props: RplButtonComponentProps) => {
  const mergedProps: Required<
    Pick<RplButtonProps, 'el' | 'url' | 'variant' | 'disabled'>
  > &
    Pick<RplButtonProps, 'label'> & {
      children?: RplButtonComponentProps['children']
    } = {
    ...rplButtonDefaults,
    ...props
  }
  const { el, url, variant, label, disabled, children } = mergedProps

  const Tag: ElementType = el === 'a' ? 'a' : 'button'
  const className = `rpl-button rpl-button--${variant} rpl-button--default rpl-u-focusable-block`

  return (
    <Tag
      href={el === 'a' ? url : undefined}
      type={el === 'button' ? 'button' : undefined}
      className={className}
      disabled={disabled || undefined}
    >
      <span className='rpl-button__label rpl-type-label rpl-type-weight-bold'>
        {label}
        {children}
      </span>
    </Tag>
  )
}

export type { RplButtonProps }

// packages/ripple-ui-vue/src/components/button/RplButton.vue
<script setup lang="ts">
import { computed, ref, inject, type Ref } from 'vue'
import type {
  RplButtonElements,
  RplButtonVariants,
  RplButtonThemes,
  RplButtonIconPositions
} from './constants'
import type { RplIconNames } from '../icon/constants'
import RplIcon from '../icon/RplIcon.vue'
import type { IRplFeatureFlags } from '@dpc-sdp/ripple-ui-shared/contracts'
import RplSpinner from '../spinner/RplSpinner.vue'

const featureFlags: IRplFeatureFlags = inject('featureFlags', {
  buttonTheme: 'default'
})

interface Props {
  el?: (typeof RplButtonElements)[number]
  url?: string
  variant?: (typeof RplButtonVariants)[number]
  theme?: (typeof RplButtonThemes)[number]
  iconName?: (typeof RplIconNames)[number]
  iconPosition?: (typeof RplButtonIconPositions)[number]
  label?: string
  disabled?: boolean
  busy?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  el: 'button',
  url: '',
  theme: undefined,
  variant: 'filled',
  iconName: undefined,
  iconPosition: 'right',
  label: undefined,
  disabled: false,
  busy: false
})

const buttonTheme = computed(() => {
  if (props.theme) {
    return props.theme
  }
  if (featureFlags?.buttonTheme) {
    return featureFlags.buttonTheme
  }
  return 'default'
})

const classes = computed(() => {
  return {
    'rpl-button': true,
    [`rpl-button--${props.variant}`]: true,
    [`rpl-button--${buttonTheme.value}`]: true,
    'rpl-u-focusable-block': true,
    'rpl-button--reverse': props.iconPosition === 'left',
    'rpl-button--busy': props.busy,
    'rpl-button--icon-only-small-screens':
      props.variant === 'elevated' && !!props.iconName
  }
})

const link: Ref = ref(null)

defineExpose({ link })

const isAnchor = computed(() => props.el === 'a')
</script>

<template>
  <component
    :is="el"
    ref="link"
    :href="isAnchor ? url : null"
    :type="el === 'button' ? 'button' : undefined"
    :class="classes"
    :disabled="disabled"
    :aria-busy="busy"
  >
    <span v-if="busy" class="rpl-button__spinner"> <RplSpinner /></span>
    <span class="rpl-button__label rpl-type-label rpl-type-weight-bold">
      <template v-if="label">
        {{ label }}
      </template>
      <slot></slot>
    </span>
    <RplIcon
      v-if="iconName"
      :name="iconName"
      class="rpl-button__icon"
      aria-hidden="true"
    ></RplIcon>
  </component>
</template>

<style src="@dpc-sdp/ripple-ui-styles/components/button/RplButton.css" />
