// packages/ripple-ui-react/src/components/alert/RplAlert.tsx
import {
  type RplAlertProps,
  rplAlertDefaults
} from '@dpc-sdp/ripple-ui-shared/contracts'
import clsx from 'clsx'
import '@dpc-sdp/ripple-ui-styles/components/alert/RplAlert.css'
import { RplIcon } from '../icon'

interface RplAlertComponentProps extends RplAlertProps {
  onClose?: (e: React.MouseEvent<HTMLButtonElement>) => void
}

export const RplAlert = (props: RplAlertComponentProps) => {
  const {
    linkText,
    linkUrl,
    variant,
    dismissed,
    alertId,
    message,
    iconName,
    isDismissible,
    onClose: onCloseCallback
  } = {
    ...rplAlertDefaults,
    ...props
  }

  const classNames = clsx({
    'rpl-alert': true,
    [`rpl-alert--${variant}`]: variant,
    'rpl-alert--closed': dismissed,
    'rpl-u-screen-only': true
  })

  const onClose = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault()
    if (onCloseCallback) {
      onCloseCallback(e)
    }
  }

  return (
    <div className={classNames}>
      {!dismissed && (
        <div
          className='rpl-alert__inner'
          role='region'
          aria-labelledby={`alert-message-${alertId}`}
        >
          <RplIcon
            className='rpl-alert__icon-info'
            size='m'
            name={iconName}
            colour='white'
            title='Alert icon'
          />
          <div className='rpl-alert__message-wrap'>
            <div
              id={`alert-message-${alertId}`}
              className='rpl-alert__message rpl-type-label rpl-type-weight-bold'
            >
              {message}
            </div>
            <a
              className='rpl-alert__link rpl-type-p rpl-u-focusable--alt-colour'
              href={linkUrl}
            >
              {linkText}
              <RplIcon
                name='icon-arrow-right'
                colour='white'
                title='Go to link'
              />
            </a>
          </div>
          {isDismissible && (
            <button
              className='rpl-alert__btn-close rpl-u-focusable-inline rpl-u-focusable--alt-colour'
              onClick={onClose}
              aria-label='Dismiss alert'
            >
              <RplIcon
                title='Dismiss alert'
                name='icon-cancel'
                colour='white'
              />
            </button>
          )}
        </div>
      )}
    </div>
  )
}

// packages/ripple-ui-core/src/components/alert/RplAlert.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import type { Ref } from 'vue'
import { RplAlertTypes } from './constants'
import onResizeHeight from '../../composables/onResizeHeight'
import { RplIconNames } from '../icon/constants'
import RplIcon from '../icon/RplIcon.vue'
import RplTextLink from '../text-link/RplTextLink.vue'

interface Props {
  variant?: RplAlertTypes
  iconName?: (typeof RplIconNames)[number]
  message?: string
  linkText?: string
  linkUrl?: string
  dismissed?: boolean
  alertId: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'information',
  iconName: 'icon-information-circle-filled',
  message: '',
  linkText: '',
  linkUrl: '',
  dismissed: false
})

const emit = defineEmits<{
  (
    e: 'dismiss',
    payload: { id: string; action: 'close'; name: string; label: string }
  ): void
}>()

const closeLabel = 'Dismiss alert'

const onClose = () => {
  emit('dismiss', {
    id: props.alertId,
    action: 'close',
    name: props.message,
    label: closeLabel
  })
}
const classes = computed(() => {
  return {
    'rpl-alert': true,
    [`rpl-alert--${props.variant}`]: props.variant,
    'rpl-alert--closed': props.dismissed,
    'rpl-u-screen-only': true
  }
})

const alertRef: Ref<HTMLDivElement | null> = ref(null)

onResizeHeight(alertRef, (height) => {
  if (alertRef.value) {
    alertRef.value.style.setProperty('--local-container-height', `${height}px`)
  }
})
</script>

<template>
  <div ref="alertRef" :class="classes">
    <div
      v-if="!dismissed"
      class="rpl-alert__inner"
      role="region"
      :aria-labelledby="`alert-message-${props.alertId}`"
    >
      <rpl-icon
        class="rpl-alert__icon-info"
        size="m"
        nopad
        :name="iconName"
      ></rpl-icon>
      <div class="rpl-alert__message-wrap">
        <div
          :id="`alert-message-${props.alertId}`"
          class="rpl-alert__message rpl-type-label rpl-type-weight-bold"
        >
          {{ message }}
        </div>
        <RplTextLink
          v-if="linkText && linkUrl"
          class="rpl-alert__link rpl-type-p rpl-u-focusable--alt-colour"
          :url="linkUrl"
        >
          {{ linkText }}<RplIcon name="icon-arrow-right" />
        </RplTextLink>
      </div>
      <button
        class="rpl-alert__btn-close rpl-u-focusable-inline rpl-u-focusable--alt-colour"
        data-cy="dismiss"
        @click="onClose"
      >
        <RplIcon :title="closeLabel" name="icon-cancel" />
      </button>
    </div>
  </div>
</template>

<style src="./RplAlert.css" />
