// packages/ripple-ui-react/src/components/accordion/RplAccordionItem.tsx
import { useEffect, type ReactNode } from 'react'
import { useAccordionContext } from './AccordionContext'
import { type RplAccordionItem as RplAccordionItemProps } from '@dpc-sdp/ripple-ui-shared/contracts'
import RplContent from './../content/RplContent'

type Props = Partial<RplAccordionItemProps> & {
  id: string
  children?: ReactNode
}

export function RplAccordionItem({
  id,
  title,
  content,
  active,
  children
}: Props) {
  const ctx = useAccordionContext()
  const { parentId, registerItem, unregisterItem, isExpanded, toggleItem } = ctx

  useEffect(() => {
    registerItem?.(id, Boolean(active))
    return () => {
      unregisterItem?.(id)
    }
  }, [id, active, registerItem, unregisterItem])

  const expanded = isExpanded(id)
  const itemId = `accordion-${parentId}-${id}`
  const contentId = `${itemId}-content`

  return (
    <li
      className={`rpl-accordion__item ${expanded ? 'rpl-accordion__item--active' : ''}`}
    >
      <button
        type='button'
        className='rpl-accordion__item-toggle'
        aria-expanded={expanded}
        aria-controls={contentId}
        id={`${itemId}-toggle`}
        onClick={() => toggleItem(id)}
      >
        <span className='rpl-accordion__item-toggle-title rpl-type-h4'>
          {title}
        </span>
      </button>
      <div
        id={contentId}
        className='rpl-accordion__item-content'
        hidden={!expanded}
      >
        <div className='rpl-accordion__item-content-inner'>
          <RplContent>
            {children ?? (
              <div dangerouslySetInnerHTML={{ __html: content ?? '' }} />
            )}
          </RplContent>
        </div>
      </div>
    </li>
  )
}

export default RplAccordionItem

// packages/ripple-ui-vue/src/components/accordion/RplAccordionItem.vue
<script lang="ts" setup>
import { inject, ref, computed, useSlots, type Ref } from 'vue'
import RplIcon from '@/components/icon/RplIcon.vue'
import RplExpandable from '@/components/expandable/RplExpandable.vue'
import { useExpandableState } from '@/composables/useExpandableState'
import { useRippleEvent, rplEventPayload } from '@/composables/useRippleEvent'
import { RplAccordionItemProps } from '@dpc-sdp/ripple-ui-shared/contracts'

const props = defineProps<RplAccordionItemProps>()

const emit = defineEmits<{
  (
    e: 'toggleAll',
    payload: rplEventPayload & { action: 'open' | 'close' }
  ): void
  (
    e: 'toggleItem',
    payload: rplEventPayload & { action: 'open' | 'close' }
  ): void
}>()

const { emitRplEvent } = useRippleEvent('rpl-accordion', emit)

const slots = useSlots()

const { sharedActiveItems, totalItems, parentId } = inject('activeItems', {
  sharedActiveItems: ref<string[]>(),
  totalItems: 0,
  parentId: ''
})

const { isItemExpanded, toggleItem } = useExpandableState(
  [],
  totalItems,
  sharedActiveItems as Ref<string[]>
)

const toggleSingle = () => {
  emitRplEvent(
    'toggleItem',
    {
      id: itemId.value,
      action: isItemExpanded(itemId.value) ? 'close' : 'open',
      text: itemTitle.value as string
    },
    { global: true }
  )

  toggleItem(itemId.value)
}

const itemId = computed(
  () => `accordion-${parentId}-${props.item?.id || props.id}`
)

const itemTitle = computed(
  () => props.item?.title || slots?.title?.()?.[0]?.children
)
</script>

<template>
  <li
    :id="itemId"
    :key="item?.id"
    :class="{
      'rpl-accordion__item': true,
      'rpl-accordion__item--active': isItemExpanded(itemId)
    }"
  >
    <button
      :id="`${itemId}-toggle`"
      class="rpl-accordion__item-toggle rpl-u-focusable-block"
      type="button"
      :aria-controls="`${itemId}-content`"
      :aria-expanded="isItemExpanded(itemId)"
      @click="toggleSingle"
    >
      <span class="rpl-accordion__item-heading-wrapper">
        <span v-if="numbered" class="rpl-accordion__item-number rpl-type-h4">
          {{ index + 1 }}
        </span>

        <span class="rpl-accordion__item-heading rpl-type-h4">
          {{ itemTitle }}
        </span>
      </span>

      <span
        class="rpl-accordion__item-icon rpl-u-screen-only"
        aria-hidden="true"
      >
        <RplIcon name="icon-chevron-down"></RplIcon>
      </span>
    </button>

    <RplExpandable
      :id="`${itemId}-content`"
      :aria-labelledby="`${itemId}-toggle`"
      :aria-hidden="isItemExpanded(itemId) === false ? 'true' : null"
      :expanded="isItemExpanded(itemId)"
      class="rpl-accordion__item-content"
    >
      <RplContent
        class="rpl-accordion__item-content-inner"
        :html="item?.content"
      >
        <slot />
      </RplContent>
    </RplExpandable>
  </li>
</template>
